### ISSUE TITLE
Inner Exception not available in MaxRetryException in a couple of scenarios (Related to #935 )

### ISSUE THREAD

**Issue by mosiddi** [elasticsearch/elasticsearch-net#1176]
Since #935 is closed, I'm opening a new issue. I've added my comments there. (https://github.com/elasticsearch/elasticsearch-net/issues/935)

A simple scenario to simulate the behavior is - 
1. Initialize NEST Client with 3 connection strings (localhost:9300, localhost:9400, localhost:9500) none of which are really ES endpoints
2. Try doing a get Index with that NEST client

**Comment by gmarz** [comment]
Hi @mosiddi 

I'm having a hard time trying to reproduce this.  Can you take a look at https://github.com/elasticsearch/elasticsearch-net/commit/b8db99a5ab8634618bc786ffac342928504acafc#diff-1ccd09a4059a3f4868fb4c32cc738557R16 and see if you could get it to fail, or spot something that we're missing?

**Comment by mosiddi** [comment]
The only difference I see in my v/s your test is I have ping disabled.

         ConnectionSettings connectionSettings = new ConnectionSettings(connectionPool)
                .DisablePing()
                .UsePrettyResponses();

**Comment by gmarz** [comment]
@mosiddi thanks :+1:.  I was able to confirm this and have proposed the above fix.

**Comment by mosiddi** [comment]
Thanks @gmarz. Appreciate it.

**Comment by mosiddi** [comment]
Awesome. Thanks!!
