### ISSUE TITLE
"Unable to connect to the remote server" when using DI

### ISSUE THREAD

**Issue by niemyjski** [elasticsearch/elasticsearch-net#1185]
I've been noticing an issue with my site hosted in azure. When I register IElasticClient as a singleton with Simple Injector after a little bit of use I start getting: "Unable to connect to the remote server" error. However elasticsearch is up and running. If I restart the website then everything works as expected. 

What is the recommended DI settings when using NEST?

**Comment by niemyjski** [comment]
Is there a Transport that does keep alive?

**Comment by gmarz** [comment]
Not out of the box, at the moment.

The default `HttpConnection` in NEST relies on .NET's [ServicePointManager](http://msdn.microsoft.com/en-us/library/system.net.servicepointmanager%28v=vs.110%29.aspx) class.  In order to enable keep alive, you have to call the [ServicePointManager.SetTcpKeepAlive](http://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.settcpkeepalive(v=vs.110).aspx) method.

We opted to not set this ourselves within `HttpConnection` because it's a global, static configuration, and may introduce some unwanted behavior in other parts of your application.

**Comment by niemyjski** [comment]
What times do you recommend? I'm currently testing with this time: https://github.com/exceptionless/Exceptionless/blob/master/Source/Core/Bootstrapper.cs#L71

**Comment by niemyjski** [comment]
I did see that you can set it on a per request basis (request.ServicePoint.SetTcpKeepAlive(bool, int, int), have you guys looked into that? That at least would make this a configuration option.

**Comment by gmarz** [comment]
Yup, we have considered setting it per request via `request.ServicePoint`, but just haven't investigated it enough to understand the consequences completely.  Perhaps this might be a good thing to look into for the next release.

As for a good timeout and interval to use...I can't really say.  I think that's pretty specific to your application and what type of load your servers are under.  I would lean to towards a smaller time initially to see if that alleviates the problem, then go from there.

**Comment by niemyjski** [comment]
I see they allow you to set the keep alive up to a thirty minute window now... http://azure.microsoft.com/blog/2014/08/14/new-configurable-idle-timeout-for-azure-load-balancer/ But this still doesn't fix it. 

After thinking about this more, I'm kind of hesitant to use the ServicePointManager. I'd rather have this option set on the request.. We may just copy an existing IConnection implementation and set it.. I'd be more than happy to test this if you guys want to add it to settings and push a release.

**Comment by niemyjski** [comment]
I see that you can add a Keep Alive header to the HttpRequestMessage but I'm pretty sure that is useless ( http://web.archive.org/web/20110605181241/http://www.io.com/~maus/HttpKeepAlive.html ).

**Comment by Mpdreamz** [comment]
To be clear the connections already use HTTP KeepAlive (default for HTTP 1/1 in .NET) and we see actual tcp connections being reused with wireshark.

The SetTCPKeepALive() method on servicepointmanager will send KeepAlive packets on those connections (at a tcp level) which by default it doesn't.

You can subclass the default connection (HttpConnection) and simply override `CreateHttpWebRequest()` first calling into base.CreateHttpWebRequest() and then alter as needed :).

You can also play with: http://msdn.microsoft.com/en-us/library/system.net.servicepoint.connectionleasetimeout%28v=vs.110%29.aspx

and http://msdn.microsoft.com/en-us/library/system.net.servicepoint.maxidletime(v=vs.110).aspx

To forcefully close connection after inactivity. 

That said if you have full exceptionmessages for us or more details on when it occurs, are you able recreate the conditions, you mentioned curl earlier what is the exact workflow there, that would be great!

**Comment by niemyjski** [comment]
I'll look into that.

 I saw that you are setting some properties on ServicePointManager that effect my whole app like Connection Limit (which seems really high and really bad), and turning off Expect 100 Continue and Nagle.... One could use ServicePointManager.FindServicePoint which would find or create a ServicePoint for an end point and allow you to configure this...

If we don't know that the connection has been terminated and we try to make a request, it throws an (not connected exception), couldn't we retry it once to reestablish the connection? It would be really nice for it to self heal..

**Comment by Mpdreamz** [comment]
Currently when you are using a single node we give up ASAP even if you specify maxretries on connectionsettings. 

When you are using ConnectionPooling we do automatically retry. So you could try to do:

```csharp
var connectionPool = new StaticConnectionPool(new [] { new Uri(..) });
var settings = new ConnectionConfiguration(connectionPool)
    .SetMaxRetries(2)
```

This is something we will revert in the next release.
