### ISSUE TITLE
ThriftConnection with SniffConnectionPool doesn't work.

### ISSUE THREAD

**Issue by christallire** [elasticsearch/elasticsearch-net#1189]
I have been using SniffConnectionPool with url designated to primary master node and just tried ThriftConnection.
I noticed that connection pool sniffed http/json binded port (9207), not thrift port(9507).
I think it should use 'thrift_address' instead of 'http_address' when using ThriftConnection

{
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "XOVBm3_gRbKNZyHMfz3jXw" : {
      "name" : "Blackbird",
      "transport_address" : "inet[/192.168.0.205:9307]",
      "host" : "memcache",
      "ip" : "192.168.0.205",
      "version" : "1.4.2",
      "build" : "927caff",
      "http_address" : "inet[/192.168.0.205:9207]",
      "thrift_address" : "/192.168.0.205:9507"
    },

... and so on
  }
}

**Comment by Mpdreamz** [comment]
Hi @christallire 

Thanks for catching this! I just realised I had not already responded to your ticket, we have fixed this in #1198 which will make it in the next release.

**Comment by christallire** [comment]
Thanks a lot for you quick response :)
