### ISSUE TITLE
The _id is not mapping back to class "Id" property if autogenerated

### ISSUE THREAD

**Issue by wallsatlarge** [elasticsearch/elasticsearch-net#1194]
For documents that the Id is autogenerated it does not map back to the matching "Id" property of the defined class.  The "IdProperty" does not see to make a difference either.  For those where the "Id" is passed in the Index method it works just fine.

Example:

 class Program
    {
        static void Main(string[] args)
        {

            var node = new Uri("http://localhost:9200");

            var settings = new ConnectionSettings(
                node,
                defaultIndex: "devtest"
            );

            var client = new ElasticClient(settings);

            var user = new User
            {
                //Id = "25",
                first_name = "Test",
                last_name = "Test",
                user_name = "testtest",
                password = "adfadsfads",
                department = "dev"
            };
            
            IndexRequest<User> tt = new IndexRequest<User>(user);
            tt.Routing = user.department;
            var index = client.Index(user);

            // Get all
            var searchResults = client.Search<User>(y => y.AllIndices());
            var users = searchResults.Documents;
        }
    }

    //[ElasticType(Name = "user", IdProperty = "Id")]
   // the "IdProperty" doesn't matter  
   public class User
    {
        public string Id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string department { get; set; }
    }

**Comment by Mpdreamz** [comment]
This is by design (although I'm open to revisit our decision). 

Id inference is read only (from c# to elasticsearch) and we will not try to do any (possibly expensive) magic post processing once `_source` comes back. 

When you are supplying your own id's on objects this prevents you having to specify id's twice. 

When are using `autogenerated ids` you will have to loop over `result.Hits` instead of `results.Documents` in a lot of autogenerated id usecases your POCO won't even have an id property.

**Comment by wallsatlarge** [comment]
Ok thanks so much for the fast response at least now I can utilize my time in adding it instead of trying to find it :)

**Comment by wallsatlarge** [comment]
Just final note your approach basically ensures anyone wanting to leverage ElasticSearch as a primary store (my case) then the solution will require a bit of extra work and abstraction to ensure the actual ID populates the key ID (whatever defined by "IdProperty").  So for future consideration I would say if you believe ElasticSearch will be support primary stores (ElasticSearch clearly does otherwise it wouldn't have added autogenerated id's) then you may reconsider adding this functionality.  As clearly is base functionality that this client does not support.
