### ISSUE TITLE
Private variables being mapped

### ISSUE THREAD

**Issue by btecu** [elasticsearch/elasticsearch-net#1199]
I have an index that has a few fields. One of the fields is an array of objects, which I previously map.
In my C# code, this custom object has only two fields:
```
private string _LastName;
public string FirstName { get; set; }
public string LastName { get { return _LastName }; set { ... }}
```
Although I specify the map correctly, my Elasticsearch ends up with all three fields and obviously _LastName and LastName are the same.

I tried `.Dynamic(DynamicMappingOption.Ignore)` and `.Dynamic(false)` on the mapping but the private string is still being logged in even if it doesn't show on the map anymore.

Any ideas?

**Comment by gmarz** [comment]
@btecu can you share your full mapping and indexing code?

**Comment by btecu** [comment]
Create the index:
```
Elasticsearch.Client.CreateIndex(c => c.Index(indexName)
	.InitializeUsing(new IndexSettings { NumberOfReplicas = 1, NumberOfShards = 5 })
	.AddMapping<Person>(m => m.MapFromAttributes())
	.AddMapping<Names>(m => m.MapFromAttributes()));
```

Index:
```
IndexAsync(person, i => i.Index(indexName));
```

Let me know if you need anything else.

**Comment by Mpdreamz** [comment]
Hi @btecu 

This is not out of the box behavior for NEST see the attached unit tests. Something in your application is instructing JSON.NET to also include private fields for serialization by setting/altering the default `DefaultMembersSearchFlags`. 

JSON.NET sadly allows you to alter the defaults globally so this might be introduced by other dependencies. See: http://james.newtonking.com/archive/2013/05/08/json-net-5-0-release-5-defaultsettings-and-extension-data
