### ISSUE TITLE
FieldIndexOption.NotAnalyzed not working on string property of nested type

### ISSUE THREAD

**Issue by nariman-haghighi** [elasticsearch/elasticsearch-net#1202]
This is on the latest NEST & ES, seems to have changed recently?

```
public class Class1
{
    [ElasticProperty(Name = "alternate_urls")
    public List<Class2> AlternateUrls { get; set; }
}

public class Class2
{
    [ElasticProperty(Index = FieldIndexOption.NotAnalyzed, Type = FieldType.String, Name = "url")]
    public string Url { get; set; }

    [ElasticProperty(Index = FieldIndexOption.NotAnalyzed, Type = FieldType.String, Name = "type")]
    public string Type { get; set; }
}
```
Results in the following mapping:
```{"type":{"type":"string"},"url":{"type":"string"}}}```

Expecting "index": "not_analyzed"

UPDATE: It seems the mappings are created correctly if we use ```MapFromAttributes``` on a new index but any ```Update``` operations on an existing index (where the property is net new) don't respect the attributes.

**Comment by Mpdreamz** [comment]
Hi @nariman-haghighi,

You can't change the analyzation settings for an existing field in an existing index, only for new fields. You will have to create a new index with the new mapping and reindex.

**Comment by nariman-haghighi** [comment]
As mentioned in the update, this was for a new field in an existing index.

**Comment by Mpdreamz** [comment]
Hi @nariman-haghighi 

I added an integration test to confirm a new field will still apply `Index = FieldIndexOption.NotAnalyzed` when introducing a new field to an existing index. 

Maybe you can use that to see what the difference with your situation might be?

**Comment by nariman-haghighi** [comment]
We tried this across 3 new fields (renaming each time), and each time it was created without "index":"not_analyzed". The difference is that we're simply updating existing documents (not calling ```.Map```) and expecting the new mappings to be applied.

**Comment by Mpdreamz** [comment]
Aye, `Map()` is an expensive operation. NEST does not figure out mapping has changed when you call `.Index()` or `.Update()` nor would you want it do so since it would involve a getmapping, compare it with reflection to a potentionally deep object graph and then call update mapping before doing any indexing every single time.
