### ISSUE TITLE
Documentation: misprint at NEST Connecting page

### ISSUE THREAD

**Issue by k-gudulin-parcsis** [elasticsearch/elasticsearch-net#1208]
Document https://github.com/elasticsearch/elasticsearch-net/blob/develop/docs/contents/nest/connecting.markdown
Line 70, link must be changed from /elasticsearch-net/connection.html to /elasticsearch-net/connecting.html

**Comment by gmarz** [comment]
Fixed.  Thanks @k-gudulin-parcsis
