### ISSUE TITLE
How to pass in a list FunctionScoreFunctions

### ISSUE THREAD

**Issue by GaryTurpin** [elasticsearch/elasticsearch-net#1216]
Currently, I only have 2 functions but I will be adding approximately 8 more in the near future and I want the code to look clean for the next person that comes along.  I know I can set it up like the following:
```c#
.Functions (
      freshness => freshnessEnabled ? freshness.Gauss(l => l.creationDate, d => d.Decay(.9).Offset("7d").Orgin(orginFreshness).Scale("3d") : null,
      distance => distanceEnabled ? distance.Gauss(l => l.location, d => d.Decay(.9).Offset("10mi").Orgin(orginDistance).Scale("10mi") : null
)
```
I want to know if there is a way to do this by passing a list/array into Functions so that I can make my method look clean after I have 10 functions.  Plus I will have a lot of conditional logic that will turn the individual functions on and off:
```c#
private List<FunctionScoreFunction> GetFunctions(){
      var list = new List<FunctionScoreFunction>();
      if (freshnessEnabled)
           list.Add(new GaussFunction<Document>(l => l.creationDate, d => d.Decay(.9).Offset("7d").Orgin(orginFreshness).Scale("3d");
      if (distanceEnabled)
           list.Add(new GaussFunction<Document>(l => l.creationDate, d => d.Decay(.9).Offset("10mi").Orgin(orginDistance).Scale("10mi");

      return list;
}

public Results Search (){
      ....
      var functions = GetFunctions();
      .Functions( functions)
      ....
}
```

**Comment by RossLieberman** [comment]
I ended up doing this by using a List<>  of Func<> and adding the items like you 


```c#
var scoringAlgorithm = new List<Func<FunctionScoreFunctionsDescriptor<T>, FunctionScoreFunction<T>>>();

//example 1:
scoringAlgorithm.Add(functions => functions
					.Gauss(fieldName.FieldName, d => d
									.Offset(string.Format("{0}d", fieldName.Offset))
									.Scale(string.Format("{0}d", fieldName.Scale))
									.Decay((double?)fieldName.Decay))
									.Weight((float)fieldName.Boost)
						);
```

Then when I want to add it to my query

```c#
var searchBuilder = new SearchDescriptor<T>();

searchBuilder.Query = (q => q.FunctionScore(fs => fs
					        		.Functions(scoringAlgorithm.ToArray())
								.Query(fsq => searchParameters.QueryContainer)
								.BoostMode(FunctionBoostMode.Sum)
								.ScoreMode(FunctionScoreMode.Sum)
					));
```

However if list was null or empty, it looked like NEST wouldn't send in the Query without it, so I added this right before the search:

```c#
//In order for ES.NET to properly search using FunctionScore. It needs to pass in an empty array if there aren't any function calculations
if (scoringAlgorithm == null || !scoringAlgorithm.Any())
	scoringAlgorithm =  new List<Func<FunctionScoreFunctionsDescriptor<T>, FunctionScoreFunction<T>>>();
```

It ends up sending an empty Functions [] array but I didn't find any impact into Elastic Search

**Comment by GaryTurpin** [comment]
Thanks!  Ill give that a try.

**Comment by GaryTurpin** [comment]
It works perfectly.  Thanks again @RossLieberman

**Comment by gmarz** [comment]
@GaryTurpin while the solution proposed by @RossLieberman works, it shouldn't be necessary- the descriptor should expose an `IEnumerable<IFunctionScoreFunction>` version of `Functions()` so that you can pass your list in directly.

I just added this in the above commit.  So in the next release you'll be able to do:

```
var functions = GetFuctions(); // returns a List<FunctionScoreFunction<T>>
.Functions(functions);
```

as you were originally looking for.

Thanks for opening this issue, and @RossLieberman thank you for replying with a work around.

**Comment by GaryTurpin** [comment]
@gmarz Ill be looking for that in the next release.  Thanks.
