### ISSUE TITLE
Planned Release date for Version 1.4.0

### ISSUE THREAD

**Issue by judewood** [elasticsearch/elasticsearch-net#1221]
Hi 
I was wondering if the planned release date for version 1.4.0 has been set yet.
Thanks
Jude Wood

**Comment by gmarz** [comment]
We just just released 1.4 as you opened this issue :) 

https://github.com/elasticsearch/elasticsearch-net/releases/tag/1.4.0

Available on NuGet as well.

**Comment by judewood** [comment]
Thank you
Jude Wood
