### ISSUE TITLE
FunctionScoreFunctionDescriptor missing filter?

### ISSUE THREAD

**Issue by GaryTurpin** [elasticsearch/elasticsearch-net#1223]
I am trying to add a function to my function score using a filter and weight but filter doesn't seem to be in the Lambda notation.  

    Query<Document>.FunctionScore(fs => fs.Functions( foo => foo.Filter())) //Doesn't exist

Here is the JSON that I am trying to reproduce in ElasticSearch.  Any suggestions on how I can accomplish this?

```
 "functions": [
                  {
                     "filter": {
                        "query": {
                           "bool": {
                              "should": [
                                 {
                                    "terms": {
                                       "titleid": [
                                          "1056",
                                          "1025"
                                       ]
                                    }
                                 }
                              ]
                           }
                        }
                     },
                     "weight": 10
                  }
]
```

**Comment by gmarz** [comment]
Hi @GaryTurpin, the correct syntax is:

```csharp
new SearchDescriptor<ElasticsearchProject>().Query(
	q => q.FunctionScore(
		fs => fs.Functions(
			f => f.Gauss("floatValue", g => g.Origin("5").Scale("0.1"))
				  .Filter(gf => gf.Term("term1", "termValue"))
				  .Weight(5)
			)
		)
	);
```

**Comment by gmarz** [comment]
@GaryTurpin sorry, I closed this issue too soon.  At a closer glance, I realized we were missing the [weight function](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#_weight), which is exactly what you're after.  Just added this in the above commit and it will be available in the next release.  Thanks for the report!

**Comment by GaryTurpin** [comment]
Thanks @gmarz.
