### ISSUE TITLE
Reference to AddJsonConverters() in xmldoc

### ISSUE THREAD

**Issue by mausch** [elasticsearch/elasticsearch-net#1225]
https://github.com/elasticsearch/elasticsearch-net/blob/15fee30ff3a09e21f1aad364aa01d52f68bfba48/src/Nest/Domain/Connection/ConnectionSettings.cs#L142 says it's "faster then adding them using AddJsonConverters()" but there is no `AddJsonConverters` method in this project.

Apparently this was a change from a previous method doing something similar ( https://github.com/elasticsearch/elasticsearch-net/commit/0ac6db144d12eff4a48217ad193a13e71e5dca49 ) but since the original method isn't there any more I found that comment confusing. Please consider removing it.

**Comment by gmarz** [comment]
Fixed.  Thanks for the report @mausch.
