### ISSUE TITLE
Histograms with specific indices - still across all indices

### ISSUE THREAD

**Issue by stevescot** [elasticsearch/elasticsearch-net#1229]
given a search descriptor like this:
{{{
 .Size(0)
                    .Indices(indices)
                    .Query(p => p.Filtered(q => q
                                                    .Filter(s => s.Term(t => t.TagName, tag))
                                    )
                    )
                    .Aggregations(
                        a => a.Filter("datefilter", f => f.
                                                             Filter(s =>
                                                                    s.Range(o => o
                                                                                     .OnField(n => n.UtcSampleTime)
                                                                                     .Greater(startTime)
                                                                                     .LowerOrEquals(endTime))
                                                             )
                                                          .Aggregations(ag2 => ag2
                                                                                   .DateHistogram("histogram",
                                                                                                  t => t
                                                                                                           .Interval(interval + "s")
                                                                                                           .Field("uTCDateTime")
                                                                                                           .Aggregations(
                                                                                                               ag => ag.Min
                                                                                                                         ("Min", tva => tva
                                                                                                                                            .Field("numValue")
                                                                                                                         )
                                                                                                                       .Max
                                                                                                                         ("Max", tva => tva
                                                                                                                                            .Field("numValue")
                                                                                                                         ))
                                                                                   )
                                                             )
                                 )

                    )
}}}

the generated query has no reference to the index / indices - meaning the aggregations are always across all indexes.

it should be across the indices passed to the search descriptor.

**Comment by stevescot** [comment]
ps. this is the json that is generated by that search request:
{
  "size": 0,
  "aggs": {
    "datefilter": {
      "filter": {
        "range": {
          "uTCDateTime": {
            "lte": "2015-02-02T13:24:19.653Z",
            "gt": "2015-01-23T13:24:19.653Z"
          }
        }
      },
      "aggs": {
        "histogram": {
          "date_histogram": {
            "field": "uTCDateTime",
            "interval": "1658.34932821497s",
            "format": "yyyy-MM-dd"
          },
          "aggs": {
            "Min": {
              "min": {
                "field": "numValue"
              }
            },
            "Max": {
              "max": {
                "field": "numValue"
              }
            }
          }
        }
      }
    }
  },
  "query": {
    "filtered": {
      "filter": {
        "term": {
          "tagName": "TI-3002"
        }
      }
    }
  }
}

**Comment by gmarz** [comment]
Hi @stevescot indices and types are specified in the request url, not the body.

Just tested this to make sure it's working, and indeed it is:

```csharp
var results = this.Client.Search<ElasticsearchProject>(s => s
	.Size(0)
	.Indices("index1", "index2")
	.Aggregations(a => a
		.Histogram("bucket_agg", m => m
			.Field(p => p.IntValues)
			.Interval(10)
		)

	)
);
```

```
{StatusCode: 404, 
  Method: POST, 
  Url: http://localhost:9200/index1%2Cindex2/elasticsearchprojects/_search?pretty=true, 
  Request: {
  "size": 0,
  "aggs": {
    "bucket_agg": {
      "histogram": {
        "field": "intValues",
        "interval": 10.0
      }
    }
  }
}
```
