### ISSUE TITLE
Upgrading NEST from 0.11.4.0 to 1.4.0 - issues with undocumented changes - AliasParams

### ISSUE THREAD

**Issue by fdahlin** [elasticsearch/elasticsearch-net#1233]
I'm currently doing an upgrade of NEST and discovered some issues that I can't find any documentation about. To start with, I can't find what would be the equivalent to Nest.AliasParams in 1.4.0 (not mentioned in http://nest.azurewebsites.net/breaking-changes.html) and how I would go about changing the following to something else in the new version:

```
                aliases.Add(new AliasParams
                {
                    Alias = aliasName,
                    Filter = restrictions.Query,
                    Index = IndexName
                });
```

Anyone that can point me in the right direction?

**Comment by gmarz** [comment]
Hi @fdahlin sorry we missed documenting this.  These tests should demonstrate how to use the new alias API: 

https://github.com/elasticsearch/elasticsearch-net/blob/develop/src/Tests/Nest.Tests.Integration/Indices/AliasTests.cs

Let me know if those are clear enough.  Happy to provide a more specific example if needed.
