### ISSUE TITLE
Reopen #858: MultiGet does not respect source filtering fields

### ISSUE THREAD

**Issue by lakario** [elasticsearch/elasticsearch-net#1235]
#858 appears to have been regressed, as early as version 1.0.2:

Just verified locally under the exact same conditions as originally. I was using version 1.0.2, and since upgraded to 1.4.0.

Here's the NEST query:

	Client.MultiGet(s =>
		s.GetMany<Performer>(termItems.Select(x => x.Term))
		.SourceInclude<Performer>(x => x.Id, x => x.Name)

And the generated request:

	http://qual-elastic002:9200/_mget?source_include=id%2Cname
	{
	  "docs": [
		{
		  "_index": "qual4-events014",
		  "_type": "performer",
		  "_id": "f6fc51e4-4198-4d32-a47a-4e0e17e025a3"
		},
		{
		  "_index": "qual4-events014",
		  "_type": "performer",
		  "_id": "98d2b8dd-0de8-4dfa-87f8-716a880fa6e0"
		}
		/* etc... */
	  ]
	}

The expected request:

    http://qual-elastic002:9200/_mget
	{
	  "docs": [
		{
		  "_index": "qual4-events014",
		  "_type": "performer",
		  "_id": "f6fc51e4-4198-4d32-a47a-4e0e17e025a3",
		  "_source": [ "id", "name" ]
		},
		{
		  "_index": "qual4-events014",
		  "_type": "performer",
		  "_id": "98d2b8dd-0de8-4dfa-87f8-716a880fa6e0",
		  "_source": [ "id", "name" ]
		}
		/* etc... */
	  ]
	}

**Comment by gmarz** [comment]
@lakario You're applying source at the query param level, hence the request url: `http://qual-elastic002:9200/_mget?source_include=id%2Cname` which applies source filtering for the entire request.

Instead, you want to set source filtering at the document level.  The syntax is a bit different:

```
Client.MultiGet(s =>s
    .GetMany<Performer>(termItems.Select(x => x.Term), gm => gm
        .Source(src => src
            .Include("id", "name")
        )
    )
)
```

**Comment by lakario** [comment]
@gmarz The above signature doesn't seem to exist for me.

    public MultiGetDescriptor GetMany<T>(IEnumerable<string> ids, Func<MultiGetOperationDescriptor<T>, string, MultiGetOperationDescriptor<T>> getSelector = null) where T : class;
    public MultiGetDescriptor GetMany<T>(IEnumerable<long> ids, Func<MultiGetOperationDescriptor<T>, long, MultiGetOperationDescriptor<T>> getSelector = null) where T : class;

Also, your example does not take advantage of the type-safe expression syntax, which is what I am after.

**Comment by lakario** [comment]
@gmarz The above signature doesn't seem to exist for me.

	public MultiGetDescriptor GetMany<T>(IEnumerable<long> ids, Func<MultiGetOperationDescriptor<T>, long, MultiGetOperationDescriptor<T>> getSelector = null) where T : class;
    public MultiGetDescriptor GetMany<T>(IEnumerable<string> ids, Func<MultiGetOperationDescriptor<T>, string, MultiGetOperationDescriptor<T>> getSelector = null) where T : class;
    
Also, your example does not take advantage of the type-safe expression syntax, which is what I am after.

**Comment by gmarz** [comment]
Oops sorry, I left out the `long` argument in the lambda.  It should be:

```
Client.MultiGet(s =>s
    .GetMany<Performer>(termItems.Select(x => x.Term), (gm, i) => gm
        .Source(src => src
            .Include(x => x.Id, x.Name)
        )
    )
)
```

Notice above, you can also use the expression form for your properties.

**Comment by lakario** [comment]
@gmarz Sure enough, that's what I was looking for. Thanks.
