### ISSUE TITLE
Missing Aggregations entries.

### ISSUE THREAD

**Issue by niemyjski** [elasticsearch/elasticsearch-net#1236]
I'm not sure if this was an issue before but I just started seeing this issue this week during testing after I upgraded to the latest nest client (1.4.0).

We have the following query we build up in code: https://github.com/exceptionless/Exceptionless/blob/feb5defda689362f4154a1c42f58c28b5618d568/Source/Core/Utility/EventStats.cs#L51-L94

which translates to the following:

		POST /events-v1-*/events/_search?search_type=count&ignore_unavailable=true
		{
		  "aggs": {
			"filtered": {
			  "filter": {
				"bool": {
				  "must": [
					{
					  "match_all": {}
					},
					{
					  "fquery": {
						"query": {
						  "query_string": {
							"query": "project:my_project_id",
							"default_operator": "and"
						  }
						}
					  }
					}
				  ]
				}
			  },
			  "aggs": {
				"terms": {
				  "terms": {
					"field": "project_id",
					"size": 25
				  },
				  "aggs": {
					"timelime": {
					  "date_histogram": {
						"field": "date",
						"interval": "150d",
						"format": "date_optional_time",
						"min_doc_count": 0,
						"time_zone": "00:00"
					  }
					},
					"unique": {
					  "cardinality": {
						"field": "stack_id",
						"precision_threshold": 1000
					  }
					},
					"new": {
					  "terms": {
						"field": "is_first_occurrence",
						"exclude": {
						  "pattern": "F"
						}
					  }
					},
					"first_occurrence": {
					  "min": {
						"field": "date"
					  }
					},
					"last_occurrence": {
					  "max": {
						"field": "date"
					  }
					}
				  }
				},
				"unique": {
				  "cardinality": {
					"field": "stack_id",
					"precision_threshold": 1000
				  }
				},
				"new": {
				  "terms": {
					"field": "is_first_occurrence",
					"exclude": {
					  "pattern": "F"
					}
				  }
				},
				"first_occurrence": {
				  "min": {
					"field": "date"
				  }
				},
				"last_occurrence": {
				  "max": {
					"field": "date"
				  }
				}
			  }
			}
		  }
		}

And this returns the following result (when I have no documents that match the query, which causes this behavior)

		{
		   "took": 3,
		   "timed_out": false,
		   "_shards": {
			  "total": 125,
			  "successful": 125,
			  "failed": 0
		   },
		   "hits": {
			  "total": 76263,
			  "max_score": 0,
			  "hits": []
		   },
		   "aggregations": {
			  "filtered": {
				 "doc_count": 0,
				 "new": {
					"doc_count_error_upper_bound": 0,
					"sum_other_doc_count": 0,
					"buckets": []
				 },
				 "first_occurrence": {
					"value": null
				 },
				 "last_occurrence": {
					"value": null
				 },
				 "terms": {
					"doc_count_error_upper_bound": 0,
					"sum_other_doc_count": 0,
					"buckets": []
				 },
				 "unique": {
					"value": 0
				 }
			  }
		   }
		}

The issue I'm seeing is in the nest client. All of the aggregations but the first two are missing:

![image](https://cloud.githubusercontent.com/assets/1020579/6067313/3726e0d6-ad39-11e4-9004-fa370fa55cf6.png)

It's worth noting that our project has a custom serializer defined. I removed it and it made no difference. It's just odd that first_occurrence can be found but last_occurrance, terms, and unique can't.

Has anyone else seen this behavior? I can get time next week to create a smaller repro if needed.

**Comment by niemyjski** [comment]
Thanks a ton!!

**Comment by niemyjski** [comment]
Any ideas when 1.4.1 will be out? I think I found all the occurrences of where I was doing aggs and added extra checks but I'd rather be safe knowing this is out there hehe

**Comment by gmarz** [comment]
No problem; thanks for the detailed report!  We're planning on getting 1.4.1 out tomorrow.
