### ISSUE TITLE
System.MissingMethodException with UpdateDescriptor using ScriptId

### ISSUE THREAD

**Issue by ivanpais** [elasticsearch/elasticsearch-net#1238]
We are receiving the MissingMethodException for methods that utilize the ScriptId method in the UpdateDescriptor method.
Simplest code to see this issue:
1. Create a method to use a sandbox script for the update with the following code:
     UpdateDescriptor<dynamic, dynamic> descriptor = new UpdateDescriptor<dynamic, dynamic>()
            .Id(id)
            .Type("test")
            .Lang("groovy")
            .ScriptId("testSandboxScript")
            .Params(p => p.Add("param1", "test"));
     IUpdateResponse updateResponse = sm_elasticSearchClient.Update<dynamic>(descriptor);
2. Have a method to call this new method. When the method gets called, you get the System.MissingMethodException type of exception.

```  _HResult=-2146233069
  _message=Method not found: 'Nest.UpdateDescriptor`2<!0,!1> Nest.UpdateDescriptor`2.ScriptId(System.String)'.
  HResult=-2146233069
  IsTransient=false
  Message=Method not found: 'Nest.UpdateDescriptor`2<!0,!1> Nest.UpdateDescriptor`2.ScriptId(System.String)'.
```

**Comment by robertlyson** [comment]
Hello @ivanpais,

Looks like you are calling this code from assembly referencing older version of NEST.
Can you make sure that you have updated all references to the NEST?

**Comment by Mpdreamz** [comment]
`ScriptId()` was added in `Nest 1.4` it looks like you are compiling against `1.4` but end up with an older reference in your `bin` folder?

**Comment by ivanpais** [comment]
Hi Robert & Martjin,
Thank you for responding on this. I did find one location where the even after updating the package, I still had an older version as well. removing this and re-installing the latest version of NEST resolved the issue.
Thank you for this.
Regards,
Ivan.
