### ISSUE TITLE
Unable to map nested type from ElasticProperty attribute

### ISSUE THREAD

**Issue by tuespetre** [elasticsearch/elasticsearch-net#1242]
I'm trying to mark a property with `FieldType.Nested`, but every time I index my object with the ElasticClient, it creates the index without mapping that property as `"type": "nested"`.

Here is my class:

```
    [ElasticType(IdProperty = "Number", Name = "serviceOrder")]
    class IndexServiceOrder
    {
        public IndexServiceOrder()
        {
            Stages = new List<Stage>();
        }

        public string Number { get; set; }

        [ElasticProperty(Name = "@timestamp")]
        public DateTime Timestamp { get; set; }

        public bool Submitted { get; set; }

        public bool Completed { get; set; }

        public string Class { get; set; }

        public string Priority { get; set; }

        [ElasticProperty(Type = FieldType.Nested)]
        public List<Stage> Stages { get; set; }

        public class Stage
        {
            public string Description { get; set; }

            public string TechGroup { get; set; }

            public string Department { get; set; }

            public bool Complete { get; set; }
        }
    }
```

Here is the mapping that is created with the index, using NEST:

```
    "serviceOrder" : {
        "properties" : {
          "@timestamp" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          },
          "class" : {
            "type" : "string"
          },
          "completed" : {
            "type" : "boolean"
          },
          "stages" : {
            "properties" : {
              "complete" : {
                "type" : "boolean"
              },
              "department" : {
                "type" : "string"
              },
              "description" : {
                "type" : "string"
              },
              "techGroup" : {
                "type" : "string"
              }
            }
          },
          "number" : {
            "type" : "string"
          },
          "priority" : {
            "type" : "string"
          },
          "submitted" : {
            "type" : "boolean"
          }
        }
      }
```

Please let me know if I'm missing something in the documentation.

**Comment by Mpdreamz** [comment]
NEST wont apply mappings when indexing, it would be too costly. 

You need to call `.Map()` or even better `.CreateIndex()` explicitly before indexing any object. 

See this test for a complete example:

https://github.com/elasticsearch/elasticsearch-net/blob/develop/src/Tests/Nest.Tests.Unit/Core/Map/FluentMappingFullExampleTests.cs#L27-L29

The highlighted line is what will make NEST pickup the attributes on your POCO. 

Hope this makes sense!

**Comment by tuespetre** [comment]
Nevermind, I finally found a related issue with the resolution:

https://github.com/elasticsearch/elasticsearch-net/issues/200

You might consider updating the documentation here to cover this scenario:

http://nest.azurewebsites.net/nest/index-type-inference.html

**Comment by tuespetre** [comment]
It was a little confusing because `Id` and `Name` properties on the `ElasticType` attribute were mapped automatically without having to call anything.

**Comment by Mpdreamz** [comment]
Hah! posted just as you found the answer.

We'll add a note to that page, thanks for the fresh view on the docs. Always invaluable.
