### ISSUE TITLE
Support for Precision and Orientation on GeoShapeMappingDescriptor<T>

### ISSUE THREAD

**Issue by russcam** [elasticsearch/elasticsearch-net#1247]
The documentation for [geo_shape](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-shape-type.html) types states that one can specify a precision and orientation for the mapping of a geo_shape type field:

**precision**

> This parameter may be used instead of tree_levels to set an appropriate value for the tree_levels parameter. The value specifies the desired precision and Elasticsearch will calculate the best tree_levels value to honor this precision. The value should be a number followed by an optional distance unit. Valid distance units include: in, inch, yd, yard, mi, miles, km, kilometers, m,meters (default), cm,centimeters, mm, millimeters.

**orientation**

> Optionally define how to interpret vertex order for polygons / multipolygons. This parameter defines one of two coordinate system rules (Right-hand or Left-hand) each of which can be specified in three different ways. 1. Right-hand rule (default): right, ccw, counterclockwise, 2. Left-hand rule: left, cw, clockwise. The default orientation (counterclockwise) complies with the OGC standard which defines outer ring vertices in counterclockwise order with inner ring(s) vertices (holes) in clockwise order. Setting this parameter in the geo_shape mapping explicitly sets vertex order for the coordinate list of a geo_shape field but can be overridden in each individual GeoJSON document

Neither are currently exposed on `GeoShapeMappingDescriptor<T>`, but it would be great if there were so that those using NEST can take adavantage of them.

**Comment by Mpdreamz** [comment]
Thanks for reporting this @russcam :+1:  submitted a PR for this yesterday 

https://github.com/elasticsearch/elasticsearch-net/pull/1248

Should make it into the next release.

**Comment by russcam** [comment]
Sweet, I'll keep an eye on the new release. Thanks for a great library!

**Comment by russcam** [comment]
Looking at the code changes in the PR, how do you supply a unit along with the precision as per the docs e.g.

	{
		"properties": {
			"location": {
				"type": "geo_shape",
				"tree": "quadtree",
				"precision": "1m"
			}
		}
	}

The PR only allows a `GeoPrecision` to be passed to the `Precision()` method.

Also, should there be some validation within the descriptor to prevent both `precision` and `tree_levels` being set?

**Comment by Mpdreamz** [comment]
doh! this is why we do pull requests to catch stupid mistakes like this :) thanks for looking it over.

will amend shortly. 

Re validation, we try to not make the client *too smart* and just send both and let the server decide how to interpret the reuqest.
