### ISSUE TITLE
SortScriptDescriptor doesn't include File property

### ISSUE THREAD

**Issue by nickelbob** [elasticsearch/elasticsearch-net#1249]
There's a File property that you can specify so that you can use a locally saved copy of a script instead of specifying one in your query. This property is missing in the SortScriptDescriptor class.

More information on this property can be found here - http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-scripting.html

**Comment by Mpdreamz** [comment]
Fixed by @nickelbob in https://github.com/elasticsearch/elasticsearch-net/pull/1250
