### ISSUE TITLE
NEST - TypeExists ignores default index

### ISSUE THREAD

**Issue by mif007** [elasticsearch/elasticsearch-net#1251]
When using a TypeExists method without specifying an Index, the DefaultIndex defined in the ElasticClient is ignored and exception "Index() is not specified" is thrown

**Comment by Mpdreamz** [comment]
Thanks for reporting this @mif007 

Most IndexTypePaths are typed and default to inferring the index from there. TypeExists uses an untyped version, I've submitted a PR to make this untyped version smarter. 

It will now use the `T` provided to `Type<T>()` as well to infer the indexname if not indexname has been explicitly provided.
