### ISSUE TITLE
Passing array to filtered terms

### ISSUE THREAD

**Issue by ZNS** [elasticsearch/elasticsearch-net#1253]
Hi,

I'm trying to pass an integer array to a filtered terms query but this doesn't seem to be possible?

```c#
.Filtered(filter => filter
    .Query(....)
    .Filter(f =>
        f.Terms(x => x.Areas, areas)
    )
)
```

To clarify. x.Areas is an integer array and areas is an integer array.

**Comment by gmarz** [comment]
@ZNS thanks for reporting!  Just pushed the above fix.
