### ISSUE TITLE
Hostname not populated in NodeStats?

### ISSUE THREAD

**Issue by BrandesEric** [elasticsearch/elasticsearch-net#1255]
I am not seeing the Hostname property of NodeStats being populated.  When I look at the code, I see this:

```C#
[JsonProperty("hostname")]
public string Hostname { get; internal set; }
```

The response from the cluster is "host" so I'm not sure how this ever works?

**Comment by gmarz** [comment]
@BrandesEric thanks for pointing this out!  It was originally `Hostname` in earlier versions of ES (< 1.0) and happened to slip past us since our NodeStats test didn't check `Hostname`.

Just pushed the above fix.  Thanks again.
