### ISSUE TITLE
Custom serializer

### ISSUE THREAD

**Issue by futurechan** [elasticsearch/elasticsearch-net#1258]
We have a case where a given index/type may actually contain multiple types. The variations are fairly small, but it may merit different classes. Is it possible to use a customer serializer to deserialize the results of a query?

**Comment by gmarz** [comment]
Hey @futurechan take a look at the Covariance section in the docs: http://nest.azurewebsites.net/nest/search/basics.html

You may be able to leverage `ConcreteTypeSelector()` as the docs describe.  A few more examples here: https://github.com/elasticsearch/elasticsearch-net/blob/develop/src/Tests/Nest.Tests.Integration/Search/SubClassSupport/SubClassSupportTests.cs
