### ISSUE TITLE
Problem Searching for Items in ES

### ISSUE THREAD

**Issue by aluink** [elasticsearch/elasticsearch-net#1259]
I'm having trouble searching for items posted to ES.  Let me give you the lay of the land first.

Here's the static logging class.

    public static class Log {
                ...
		public static Task Indeed(IndeedLog wse) {
			wse.Timestamp = DateTime.Now;

			return IndexWebservice(wse);
		}

                private static Task IndexWebservice<T>(T webservice) where T : class {
			var indexName = "webservices-" + String.Format("{0:yyyy.MM.dd}", DateTime.Now);

			// Daily webservice index must be created if it hasn't been already
			if (!Elasticsearch.Cluster.Indices.Contains(indexName)) {
				Elasticsearch.Client.CreateIndex(c => c.Index(indexName)
					.InitializeUsing(new IndexSettings { NumberOfReplicas = 1, NumberOfShards = 5 })
					.AddMapping<WebserviceLog>(m => m.MapFromAttributes())
					.AddMapping<IndeedLog>(m => m.MapFromAttributes())
					.AddMapping<BackgroundCheck>(m => m.MapFromAttributes()));

				Elasticsearch.Cluster.UpdateIndex(indexName);
			}

			return Elasticsearch.Client.IndexAsync(webservice, i => i.Index(indexName).Refresh());
		}
                ...
     }

Here's our logged POCO.

        [ElasticType(Name = "indeed")]
    public class IndeedLog {
		[ElasticProperty(Type = FieldType.String, Index = FieldIndexOption.NotAnalyzed)]
		public string Id { get; set; }
		[ElasticProperty(Name = "@timestamp")]
		public DateTime Timestamp { get; set; }
		public string RawJson { get; set; }
	}

And finally a singleton class to setup our connection to ES

       public class Elasticsearch {
		// Static holder for instance
		private static readonly Lazy<Elasticsearch> Connection = new Lazy<Elasticsearch>(() => new Elasticsearch());
		private static readonly StaticConnectionPool Pool = new StaticConnectionPool(new[] { new Uri("http://log1.ourserver.com:9200"), new Uri("http://log2.ourserver.com:9200") });

		/// <summary>
		/// Elasticsearch client
		/// </summary>
		private ElasticClient ElasticClient { get; set; }

		// Private constructor to prevent direct instantiation
		private Elasticsearch() {
			var settings = new ConnectionSettings(Pool);

			// Default map type is required because there's no default index
			settings.MapDefaultTypeIndices(m => m.Add(typeof(EmailLog), "emails-*"));
			settings.MapDefaultTypeIndices(m => m.Add(typeof(Session), "sessions-*"));
			settings.MapDefaultTypeIndices(m => m.Add(typeof(SessionHit), "sessions-*"));
			settings.MapDefaultTypeIndices(m => m.Add(typeof(IndeedLog), "webservices-*"));
			settings.MapDefaultTypeIndices(m => m.Add(typeof(BackgroundCheck), "webservices-*"));

			ElasticClient = new ElasticClient(settings);

			Indices = new List<string>();
		}

		// Public accessors
		public static Elasticsearch Cluster {
			get { return Connection.Value; }
		}

		public static ElasticClient Client {
			get { return Connection.Value.ElasticClient; }
		}

		// Current indices
		public List<string> Indices { get; private set; }

		public void UpdateIndex(string indexName) {
			var index = indexName.Split('-')[0];

			if (!Indices.Any(x => x.Contains(index))) {
				Indices.Add(indexName);
				return;
			}

			for (var i = 0; i < Indices.Count; i++) {
				if (Indices[i].Contains(index)) {
					Indices[i] = indexName;
					return;
				}
			}
		}
	}

So I have an action in our system that posts to ES by simply doing something like 
    Log.Indeed(new IndeedLog{ Id = GUID.ToString(), RawJson = "{}"})

And up until recently, I was able to pull that item back out with the following. GUID is the same guid used to post it (it's being passed around with a message queue).
    Elasticsearch.Client.Search<IndeedLog>(il => il.Query(q => q.Term(t => t.Id, GUID))).Documents

Myself and my teammate that setup the system spent over half the day trying to figure out why we can't pull items back out.  We've run out of ideas on what it could be.  So we come humbly to this forum looking for ideas/solutions.

From the singleton, you might notice how we have a few other POCOs we post.  Session, for instance, has no problems being retrieved.  I've compared both processes and as far as I can tell, they are posted and retrieved the exact same way.

TIA,
Eric

**Comment by gmarz** [comment]
Hey @aluink sorry for the slow reply.  Have you figured this out yet?  If not, mind posting the contents of `ConnectionStatus` from the response?

**Comment by aluink** [comment]
Hey Greg,

We actually got it working.  Now that I read it, that code up there isn't exactly what we had when it was having issues.  What is posted is quite close to what we have now that works.  The original code had the POCO inheriting from another one.

        public static Task Webservice(WebserviceLog wse) {
			wse.Timestamp = DateTime.Now;

			return IndexWebservice(wse);
	}

        private static Task IndexWebservice<T>(T webservice) where T : WebserviceLog {
			var indexName = "webservices-" + String.Format("{0:yyyy.MM.dd}", DateTime.Now);

			// Daily webservice index must be created if it hasn't been already
			if (!Elasticsearch.Cluster.Indices.Contains(indexName)) {
				Elasticsearch.Client.CreateIndex(c => c.Index(indexName)
					.InitializeUsing(new IndexSettings { NumberOfReplicas = 1, NumberOfShards = 5 })
					.AddMapping<WebserviceLog>(m => m.MapFromAttributes())
					.AddMapping<IndeedLog>(m => m.MapFromAttributes())
					.AddMapping<BackgroundCheck>(m => m.MapFromAttributes()));

				Elasticsearch.Cluster.UpdateIndex(indexName);
			}

			return Elasticsearch.Client.IndexAsync(webservice, i => i.Index(indexName).Refresh());
		}

	[ElasticType(Name = "webservice")]
	public abstract class WebserviceLog {
		[ElasticProperty(Type = FieldType.String, Index = FieldIndexOption.NotAnalyzed)]
		public string Id { get; set; }
		[ElasticProperty(Name = "@timestamp")]
		public DateTime Timestamp { get; set; }
	}

	[ElasticType(Name = "indeed")]
	public class IndeedLog : WebserviceLog {
		public string RawJson { get; set; }
	}

	[ElasticType(Name = "backgroundCheck")]
	public class BackgroundCheck : WebserviceLog {
		public string Provider { get; set; }
		public string Data { get; set; }
	}

Our current working solution is to have it all in a single class like this: 

	[ElasticType(Name = "webservice")]
	public class WebserviceLog {
		[ElasticProperty(Type = FieldType.String, Index = FieldIndexOption.NotAnalyzed)]
		public string Id { get; set; }
		[ElasticProperty(Name = "@timestamp")]
		public DateTime Timestamp { get; set; }
		public string Provider { get; set; }
		public string Data { get; set; }
	}

The rest of the code is the same as my first post.  We really liked the benefits of the inherited model.  Do you happen to know why it would give us problems?  Are inherited POCOs supported by the API?

**Comment by gmarz** [comment]
Yes, inheritance is supported.

Shooting from the hip here since I don't know the full query you're executing, but since you don't have a default index mapped to `WebserviceLog`, if you call `Search<WebserviceLog>(...)` and pass it an instance of `BackgroundCheck` or `IndeedLog`, NEST is going to use `WebserviceLog` to infer the index and not the latter two types which you are mapping to `webservices-*`.

Try adding:

```csharp
settings.MapDefaultTypeIndices(m => m.Add(typeof(WebserviceLog), "webservices-*"));
```

Also, unrelated but you may also want to use a term **filter** here instead of a query:

```csharp
il => il.Query(q => q.Term(t => t.Id, GUID))
```

to take advantage of the bitset caching in Elasticsearch.  More on that [here](http://www.elasticsearch.org/blog/all-about-elasticsearch-filter-bitsets/).

**Comment by aluink** [comment]
Alright, great. Knowing that inheritance is supported gives me the hope of knowing it can work.  When I get some breathing room in my project cycle, I'll try to work it back in.

Thanks for the help.  I'll close this for now, but I may comment again when I find time to work on it some more.
