### ISSUE TITLE
Odd filter difference between Nest and Sense

### ISSUE THREAD

**Issue by djnelson9715** [elasticsearch/elasticsearch-net#1264]
In my nest code, I have the following code:

            var unresolved = _sourceElasticClient.Search<SearchTrackWithDevice>(s => s
                   .Query(q => q
                       .Filtered(fq => fq
                           .Filter(f => f
                               .Bool(b => b
                                   .Must(m => m
                                       .Missing(mis => mis
                                           .Browser.BrandName))
                                   .MustNot(mn => mn
                                       .Term(t=>t.UserAgent, string.Empty))))))
                                       .Aggregations(ag=>ag
                                           .Terms(UserAgentTermAgg, t=>t
                                               .Field(f=>f
                                                   .UserAgent)
                                                   .Size(NumberOfTerms))));

I am specifically excluding records with an empty UserAgent string.  This field is not analyzed.

Those records with an empty UserAgent are being returned in the aggregation.
With this in Sense, I am getting the results I would expect.

GET searchtrackinfo/SearchClickWithBrowser/_search?search_type=count
{
  "query": {"filtered": {
    "query": {"match_all": {}},
    "filter": {
      "bool": {"must": [
        {"missing": {
          "field": "browser.brandName"
        }}
      ], "must_not": [
        {"term": {
          "userAgent": ""
        }}
      ]}
    }
  }},"aggs": {
    "userAgentTermAgg": {
      "terms": {
        "field": "userAgent",
        "size": 1000
      }
    }
  }
}

Those records without the user agent are being excluded as expected.

I am currently running 1.4.2 elastic and also using the 1.4.2 Nest client.

Thanks in advance

**Comment by gmarz** [comment]
Hey @djnelson9715 this behavior is due to the `conditionless` construct was added to NEST in 1.0: https://github.com/elasticsearch/elasticsearch-net/issues/414.  Check out [this blog post](http://www.elasticsearch.org/blog/introducing-elasticsearch-net-nest-1-0-0-beta1/) for a good explanation of the feature.

You can disable it by adding `.Strict()` to the query:

```csharp
 .Query(q => q
     .Strict()
     .Filtered(fq => fq
```
