### ISSUE TITLE
Do not include .pdb files to nuget package, create separate .symbols.nupkg package instead

### ISSUE THREAD

**Issue by maximpashuk** [elasticsearch/elasticsearch-net#436]
Consider to NuGet documentation
http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-symbol-package

Instead of including .pdb files to .nupkg directly, use -Source nuget option to generate special type of package - .symbols.nupkg package that keep pbd files and sources.
Publish main package to nuget.org and symbols package to symbolsource.org - this canbe arrived by one command.

None of popular nuget packages (newtonsoft.json for example) include pdb files.
NEST nuget package also should not contain pdb files, pdb and sources should be available at symbolsource.org

**Comment by Mpdreamz** [comment]
Closing this because we now ship with gitlink indexing our source.
