### ISSUE TITLE
Support for TCompactProtocol in Thrift protocol

### ISSUE THREAD

**Issue by maximpashuk** [elasticsearch/elasticsearch-net#573]
As you can see in sources of thrift plugin for elasticsearch:

https://github.com/elasticsearch/elasticsearch-transport-thrift/blob/master/src/main/java/org/elasticsearch/thrift/ThriftServer.java#L82-L86

Supported protocols are TBinaryProtocol and TCompactProtocol (binary y default).

As I can see in sources on ThriftConnetion

https://github.com/elasticsearch/elasticsearch-net/blob/d5a743d4f3b6863a20e0c4b3e95342b8a6025e60/src/Connections/Elasticsearch.Net.Connection.Thrift/ThriftConnection.cs#L41

Only TBinaryProtocol is supported.
Please add support of TCompactProtocol, it is more effective that TBinaryProtocol.

**Comment by Mpdreamz** [comment]
this has been implemented by @robertlyson as per #1157
